name: DiscordBanAnnouncer
version: '${project.version}'
main: me.headzz.discordbanannouncer.DiscordBanAnnouncer
description: "Allows you to log LiteBans related activity to a discord channel"
api-version: 1.13
authors:
  - Headzz
  - Hellin
softdepend: [LiteBans]